# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: HH.CODING
email: dkdemfp2@naver.com
description: VR and Unity and many other tries..
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://hyounghokim.github.io" # the base hostname & protocol for your site
github_username:  HyoungHoKim
paginate: 5
theme-dark: false #Set to true to change to dark website theme

plugins: [jekyll-paginate, kramdown]
# Build settings
markdown: kramdown
google_analytics: 'G-WPJ7RZNZTE'
disqus-shortname: hyounghokim-github-io
